server:
  port: 8080 # Port de ton tableau de bord CI/CD

spring:
  # 1. Authentification GitHub OAuth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "Ov23liJOqVT63MzuaEl8"
            client-secret: "3b41a7cc71a4e5b601f44e992aedf312905eea1d"
            scope:
              - read:user
              - repo        # Pour lire tes projets sur GitHub
              - admin:repo_hook # Utile pour créer des Webhooks automatiquement

  # 2. Base de données pour l'application CI/CD
  # On utilise MongoDB comme ton projet métier pour rester cohérent
  data:
    mongodb:
      uri: mongodb://localhost:27017/cicd_manager 

# 3. Configuration de la VM de Production (Ta Kali)
# Ces variables seront utilisées par ton code Java pour se connecter en SSH
production:
  vm:
    ip: "10.114.252.40"
    user: "kali"
    password: "kali" # Ou utilise une clé SSH pour plus de sécurité (recommandé)
    ssh-port: 22

# 4. Chemins des Microservices (Pour le Build Maven)
project:
  modules:
    - name: "auth-api"
      path: "./auth-api"
    - name: "monstre-api"
      path: "./monstre-api"
    - name: "player-api"
      path: "./player-api"
    - name: "invocation-api"
      path: "./invocation-api"