services:
  backend:
    image: ghcr.io/guizaouiadam1234/cloud-securise-backend:${BACKEND_IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  frontend:
    image: ghcr.io/guizaouiadam1234/cloud-securise-frontend:${FRONTEND_IMAGE_TAG}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
